# Generated by Django 5.0.4 on 2024-04-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_authorizationuser_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationuser',
            name='invite_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
