# Generated by Django 5.0.4 on 2024-04-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_authorizationuser_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuser',
            name='phone_number',
            field=models.IntegerField(max_length=30, unique=True),
        ),
    ]
