# Generated by Django 5.0.4 on 2024-04-20 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_authorizationuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='authorizationuser',
            name='invite_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.invitecode'),
        ),
    ]
