# Generated by Django 5.0.4 on 2024-04-20 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_invitecode_alter_authorizationuser_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.invitecode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.authorizationuser')),
            ],
        ),
    ]
