# Generated by Django 5.0.4 on 2024-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_friendscode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendscode',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='friendscode',
            name='invite_code',
            field=models.ManyToManyField(null=True, to='user.invitecode'),
        ),
    ]
