# Generated by Django 5.0.4 on 2024-04-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_friendscode_invite_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationuser',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='friendscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='friendscode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.authorizationuser'),
        ),
    ]
