# Generated by Django 5.0.4 on 2024-04-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_authorizationuser_invite_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendsCode',
            new_name='Referral',
        ),
    ]
