# Generated by Django 5.0.4 on 2024-04-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_friendscode_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='referral',
            name='invite_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.invitecode'),
        ),
    ]
