# Generated by Django 5.0.4 on 2024-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_referral_invite_code_referral_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuser',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
